#ifndef INFERENCE_ENGINE_MODEL_DESCRIPTOR_H
#define INFERENCE_ENGINE_MODEL_DESCRIPTOR_H

#include "inference_engine.h"
#include "inference_engine_operators.h"
#include "inference_engine_export.h"

#ifdef __cplusplus
extern "C" {
#endif


typedef struct _inference_engine_model_descriptor_t* inference_engine_model_descriptor_t;
typedef struct _inference_engine_model_t* inference_engine_model_t;

INFERENCE_ENGINE_API inference_engine_model_descriptor_t inferenceEngineCreateModelDescriptor(inference_engine_node_t* out_nodes, uint32_t out_nodes_count);
INFERENCE_ENGINE_API void inferenceEngineDestroyModelDescriptor(inference_engine_model_descriptor_t md);
INFERENCE_ENGINE_API inference_engine_model_t inferenceEngineCompileModelDescriptor(inference_engine_context_handle_t context, inference_engine_stream_t stream, inference_engine_model_descriptor_t model_desc);
INFERENCE_ENGINE_API inference_engine_result_t inferenceEngineExecuteModel(inference_engine_model_t model, inference_engine_stream_t stream);

#ifdef __cplusplus
}
#endif

#endif  // INFERENCE_ENGINE_MODEL_DESCRIPTOR_H